# Generated by Django 4.2.2 on 2023-06-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, upload_to="Catalog/images/"),
        ),
    ]
