# Generated by Django 4.2.2 on 2023-07-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0002_product_image2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="url",
        ),
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default="DEFAULT", max_digits=10
            ),
        ),
    ]
