# Generated by Django 4.2.2 on 2023-07-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0002_product_image3_product_image4_product_image5_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="available",
            new_name="preorder",
        ),
    ]
