# Generated by Django 4.2.2 on 2023-07-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0003_remove_product_url_product_available_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default="DEFAULT VALUE", max_digits=10
            ),
        ),
    ]
