# Generated by Django 4.2.2 on 2023-07-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0005_alter_product_description_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                default="S",
                max_length=2,
            ),
        ),
    ]
