# Generated by Django 4.2.2 on 2023-07-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0006_product_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                default="S",
                max_length=10,
            ),
        ),
    ]
