# Generated by Django 4.2.2 on 2023-08-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0007_remove_product_sizes_product_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image5",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image6",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image7",
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="Catalog/images/", verbose_name="Фото"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Catalog.product",
                    ),
                ),
            ],
        ),
    ]
